currentSettings: ${self:custom.environment.stages.${self:provider.stage}}

shared: &shared
  AUTH_ARN: arn:aws:cognito-idp:ap-southeast-2:457286094131:userpool/ap-southeast-2_G3sdlJ96i
  SNS_BASE_ARN: 'arn:aws:sns:ap-southeast-2:457286094131:'
  DYNAMO_BASE: 'arn:aws:dynamodb:ap-southeast-2:457286094131:table'
  USERS_TABLE: ${self:provider.environment.DYNAMO_BASE}/${self:provider.environment.TABLE_PREFIX}USERS
  NOTIFY_USER_TOPIC: notify-user-plate-recognition-${self:provider.stage}
  NOTIFY_USER_TOPIC_ARN: ${self:provider.environment.SNS_BASE_ARN}${self:provider.environment.NOTIFY_USER_TOPIC}
  USER_SERVICE_TOPIC: user-service-${self:provider.stage}
  USER_SERVICE_TOPIC_ARN: ${self:provider.environment.SNS_BASE_ARN}${self:provider.environment.USER_SERVICE_TOPIC}
  PLATE_SERVICE_TOPIC: plate-service-${self:provider.stage}
  PLATE_SERVICE_TOPIC_ARN: ${self:provider.environment.SNS_BASE_ARN}${self:provider.environment.PLATE_SERVICE_TOPIC}

preProdShared: &preProdShared
  <<: *shared

stages:
  dev:
    <<: *preProdShared
    TABLE_PREFIX: -STAGING
    STRIPE_SECRET_KEY: ${ssm:STRIPE_TEST_SECRET_KEY}
    STRIPE_PUBLIC_KEY: ${ssm:STRIPE_TEST_PUBLIC_KEY}

  staging:
    <<: *preProdShared
    TABLE_PREFIX: -STAGING
    STRIPE_SECRET_KEY: ${ssm:STRIPE_TEST_SECRET_KEY}
    STRIPE_PUBLIC_KEY: ${ssm:STRIPE_TEST_PUBLIC_KEY}

  prod: &prod
    <<: *shared
    TABLE_PREFIX: -PROD
    STRIPE_SECRET_KEY: ${ssm:STRIPE_SECRET_KEY}
    STRIPE_PUBLIC_KEY: ${ssm:STRIPE_PUBLIC_KEY}
