currentSettings: ${self:custom.environment.stages.${self:provider.stage}}

shared: &shared
  AUTH_ARN: arn:aws:cognito-idp:ap-southeast-2:457286094131:userpool/ap-southeast-2_G3sdlJ96i

preProdShared: &preProdShared
  <<: *shared

stages:
  dev:
    <<: *preProdShared
    TABLE_PREFIX: STAGING-
    STRIPE_SECRET_KEY: ${ssm:STRIPE_TEST_SECRET_KEY}
    STRIPE_PUBLIC_KEY: ${ssm:STRIPE_TEST_PUBLIC_KEY}

  staging:
    <<: *preProdShared
    TABLE_PREFIX: STAGING-
    STRIPE_SECRET_KEY: ${ssm:STRIPE_TEST_SECRET_KEY}
    STRIPE_PUBLIC_KEY: ${ssm:STRIPE_TEST_PUBLIC_KEY}

  prod: &prod
    <<: *shared
    TABLE_PREFIX: PROD-
    STRIPE_SECRET_KEY: ${ssm:STRIPE_SECRET_KEY}
    STRIPE_PUBLIC_KEY: ${ssm:STRIPE_PUBLIC_KEY}
